### PR TITLE
Transpose

### PR DESCRIPTION
**Pull request by sathvikrav**
Modifies the tabtranspose table functionality by adding the alignment parameter as the third parameter with the default value being "n" for no. Parameter only accepts a single char "y" or "n" and is case insensitive. Below is a sample use functionality of the tab transpose function:

image

### CODE REVIEW

**Comment by teuben** [comment]
sorry, should have been clear. For booleans (a true/false) we have a special getbparam() function, it will accept 0/1/y/n/t/f and doesn't care about case.   So
      bool Qalign  = getbparam("align")
would be the example setting, and then you can treat it like
   if (Qalign) 
       // true case
   else
      ///false case

can you also add the modified tabtranspose.1 manual to the pull request.

**Comment by sathvikrav** [comment]
I don't think the getbparam function works with 0 or 1. 

image

**Comment by teuben** [comment]
This could be a bug then

**Comment by teuben** [comment]
There is a new version of getparam, it will properly parse booleans and allow a much wider (also multilingual) range of responses to true/false, even classy .TRUE. and .FALSE. from the fortran age.

**Pull request closed without merging**
