### PR TITLE
activate mknemo unsio && uns_projects

### PR DESCRIPTION
**Pull request by jcldc**
Hi Peter,
I have modified src/scripts/mknemo.d/unsio && uns_projects to compile this 2 projects.
The only requirement is to have `cmake` tools + `hdf5 dev` files. Then it should compile.

A simple `mknemo uns_projects` would compile and install unsio lib, and also compile all uns_projects binaries 
- uns2uns : convert uns files (nemo, ramses, gadget2, gadget3) to (nemo, gadget2, gadget3)
- uns_density : to compute density using falcON (most wanted programs)
- uns_2dplot, etc.....
These binaries are moved automatically into NEMOBIN.

Could you try by yourself ?

### CODE REVIEW

**Comment by teuben** [comment]
I got this error
..../usr/jcl/uns_projects/lib/projects/nemodep/cbar.cc:16:10: fatal error: uns.h: No such file ....

I do see it in 
      inc/uns/uns.h

When I cheat, and copy them into inc, I get -lunsio not found
and in the lib I see
      x86_64-linux-gnu/libnemomaing77.a x86_64-linux-gnu/libunsio.so

The idea of current NEMO is that we push everything in $NEMO/lib, 
the $NEMOINC/uns is ok, but the code needs  to #include <uns/uns.h>, or add a new -I flag.... I prefer the  uns/uns.h approach.

**Comment by jcldc** [comment]
Ok I have an idea, I made my test on mageia and it looks like you did yours on ubuntu. I see the pb. I will try to fix it tomorrow.

**Comment by jcldc** [comment]
Ok I fixed the issues. 
I did not modify anything on  nemo_uns branch, only on my git repositories unsio and uns_projects. 
To re-compile, you could just do the following  (from nemo_uns branch):
```
cd $NEMO/usr/jcl
rm -rf unsio uns_projects
mknemo uns_projects
```
then you should get access to :
- uns_info 
- uns_density 
- un2uns 
- uns_2dplot 
- uns_tonemo 
- uns_addgravity

JC

**Comment by teuben** [comment]
Still failing. I'm going to try mageia in a virtualbox. 

My current error or more "deja vu":

[ 28%] Linking CXX executable bin/uns_snapgif
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libpgplot.a(pndriv.o): undefined reference to symbol 'png_write_row@@PNG16_0'
//usr/lib/x86_64-linux-gnu/libpng16.so.16: error adding symbols: DSO missing from command line

**Comment by jcldc** [comment]
> Still failing. I'm going to try mageia in a virtualbox.
 Well not necessary I think.
 It worked both for me on mageia6 and ubuntu19.10.
 Did you try from a fresh nemo_uns branch  install ?

**Comment by jcldc** [comment]
And btw, I should remove `uns_snapgif` which is useless

**Comment by teuben** [comment]
I did the whole procedure from scratch. I used the following:  (you will need the new version 1.1 of the install_nemo.sh script, I had to add the branch= keyword option)

./install_nemo.sh branch=nemo_uns mknemos=hdf5 yapp=ps check=0 bench=0
source nemo/nemo_start.sh
mknemo uns_projects

and now it works :-)    I don't know why it failed before, as i was on the right branch and removed the source directories. But here you have it.

I'm ready to merge!

**Comment by jcldc** [comment]
Ok you have merged that's great.
But I wanted to tell you that unsio (lib) needs sqlite3-dev to compile, may be it should be specify somewhere in the install_nemo.sh script

**Comment by teuben** [comment]
I'll add this to the requirements. On ubuntu it's called libsqlite3-dev, which I happen to have.
It's not part of the default install.  
I see that github gives me the option to delete the branch, what's your thought on this?

**Comment by jcldc** [comment]
>  I see that github gives me the option to delete the branch, what's your thought on this?

Yes sure delete !

**Comment by jcldc** [comment]
By the way,
now that you  have uns_projects software, can try something like this :
```
mkspiral - nbody=10000| gyrfalcON - - step=0 eps=0.05 kmax=6 logfile=/dev/null | uns_density - - all | glnemo2 - all play=t
```

**Comment by teuben** [comment]
Indeed, this is very cool.   I had two problems:
1)  the uns_snapgif tool has build issues, as we discussed before.   I added the -i flag to make to get around it. Or as you said, you could remove it?
2) then evrything built fine, but somehow uns_density (and a few more) were not copied to $NEMOBIN.

**Comment by jcldc** [comment]
OK I will fix this issues on Monday

**Pull request merged**
